ATSuite C++: ODESolvers.hpp File Reference
ODESolvers.hpp File Reference
Ordinary differential equation solvers.
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
Functions
gsl_matrix * generateCuspEuler (gsl_vector *state, double r, double h, double length, double dt, int sampling, double spinup)
Integrate the cusp normal form with an Euler scheme.
gsl_vector * cuspEuler (gsl_vector *state, double r, double h, double dt)
Integrate one step forward the cusp normal form with an Euler scheme.
gsl_vector * cuspField (gsl_vector *state, double r, double h)
Get the field of the normal form of the cusp at a given state.
gsl_matrix * generateLorenzRK4 (gsl_vector *state, double rho, double sigma, double beta, double length, double dt, int sampling, double spinup)
Integrate the Lorenz, 1963 with an RK 4 scheme.
gsl_vector * lorenzRK4 (gsl_vector *state, double rho, double sigma, double beta, double dt)
Integrate one step forward the Lorenz, 1963 with an RK4 scheme.
gsl_vector * lorenzField (gsl_vector *state, double rho, double sigma, double beta)
Get the field of the Lorenz, 1963 at a given state.
Detailed Description
ATSuite ordinary differential equation solvers.
Definition in file ODESolvers.hpp.
Function Documentation
gsl_vector * cuspEuler (gsl_vector * state, double r, double h, double dt)
Integrate one step forward the cusp normal form (see Strogatz, 1994) with an Euler scheme.
Parameters
[in] state Present state.
[in] r Parameter r.
[in] h Parameter h.
[in] dt Time step.
Returns
GSL vector of the future state.
Definition at line 78 of file ODESolvers.hpp.
References cuspField().
Referenced by generateCuspEuler().
gsl_vector * cuspField (gsl_vector * state, double r, double h)
Get the field of the normal form of the cusp at a given state.
Parameters
[in] state State.
[in] r Parameter r.
[in] h Parameter h.
Returns
GSL vector of the field at the state.
Definition at line 101 of file ODESolvers.hpp.
Referenced by cuspAdditiveWienerEM(), and cuspEuler().
gsl_matrix * generateCuspEuler (gsl_vector * state, double r, double h, double length, double dt, int sampling, double spinup)
Integrate the cusp normal form (see Strogatz, 1994) with an Euler scheme.
Parameters
[in] state Initial state.
[in] r Parameter .
[in] h Parameter .
[in] length Length of integration.
[in] dt Time step.
[in] sampling Step between each sampled state.
[in] spinup Lenght of initial spinup period to discard.
Returns
GSL matrix recording the integration.
Definition at line 38 of file ODESolvers.hpp.
References cuspEuler().
gsl_matrix * generateLorenzRK4 (gsl_vector * state, double rho, double sigma, double beta, double length, double dt, int sampling, double spinup)
Integrate the Lorenz, 1963 with an Runge-Kutta 4 scheme.
Parameters
[in] state Initial state.
[in] rho Parameter .
[in] sigma Parameter .
[in] beta Parameter .
[in] length Length of integration.
[in] dt Time step.
[in] sampling Step between each sampled state.
[in] spinup Lenght of initial spinup period to discard.
Returns
GSL matrix recording the integration.
Definition at line 128 of file ODESolvers.hpp.
References lorenzRK4().
gsl_vector * lorenzField (gsl_vector * state, double rho, double sigma, double beta)
Get the field of the Lorenz, 1963 at a given state.
Parameters
[in] state State.
[in] rho Parameter .
[in] sigma Parameter .
[in] beta Parameter .
Returns
GSL vector of the field at the state.
Definition at line 226 of file ODESolvers.hpp.
Referenced by lorenzLinearWienerEM(), and lorenzRK4().
gsl_vector * lorenzRK4 (gsl_vector * state, double rho, double sigma, double beta, double dt)
Integrate one step forward the Lorenz, 1963 with an Runge-Kutta 4 scheme.
Parameters
[in] state Present state.
[in] rho Parameter .
[in] sigma Parameter .
[in] beta Parameter .
[in] dt Time step.
Returns
GSL vector of the future state.
Definition at line 171 of file ODESolvers.hpp.
References lorenzField().
Referenced by generateLorenzRK4().