ATSuite C++: SDESolvers.hpp File Reference
SDESolvers.hpp File Reference
Stochastic differential equation solvers.
#include <cmath>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <ODESolvers.hpp>
Functions
gsl_matrix * generateCuspAdditiveWienerEM (gsl_vector *state, double r, double h, gsl_matrix *noiseSamples, double Q, double length, double dt, int sampling, double spinup)
Integrate the cusp normal form with additive Wiener and EM scheme.
gsl_matrix * generateCuspAdditiveWienerEM (gsl_vector *state, double r, gsl_vector *hTransient, gsl_matrix *noiseSamples, double Q, double length, double dt, int sampling, double spinup)
Transient int. of the cusp normal form with additive Wiener and EM scheme.
gsl_vector * cuspAdditiveWienerEM (gsl_vector *state, double r, double h, gsl_vector *noiseSample, double Q, double dt)
Integrate one step the cusp normal form with an additive Wiener and EM scheme.
gsl_matrix * generateLorenzLinearWienerEM (gsl_vector *state, double rho, double sigma, double beta, gsl_matrix *noiseSamples, double Q, double length, double dt, int sampling, double spinup)
Integrate the Lorenz, 1963 with multiplicative linear Wiener and EM scheme.
gsl_vector * lorenzLinearWienerEM (gsl_vector *state, double rho, double sigma, double beta, gsl_vector *noiseSample, double Q, double dt)
Integrate one step the Lorenz, 1963 with multiplicative linear Wiener, and EM Scheme.
gsl_vector * additiveWienerField (double Q, gsl_vector *noiseSample)
Get the field of the additive Wiener.
gsl_vector * linearWienerField (gsl_vector *state, double Q, gsl_vector *noiseSample)
Get the field of the multiplicative linear Wiener.
Detailed Description
ATSuite stochastic differential equation solvers.
Definition in file SDESolvers.hpp.
Function Documentation
gsl_vector * additiveWienerField (double Q, gsl_vector * noiseSample)
Get the field of the additive Wiener process.
Parameters
[in] Q Noise intensity.
[in] noiseSample GSL vector of noise realization for this time step.
Returns
GSL vector of the field at the state.
Definition at line 343 of file SDESolvers.hpp.
Referenced by cuspAdditiveWienerEM().
gsl_vector * cuspAdditiveWienerEM (gsl_vector * state, double r, double h, gsl_vector * noiseSample, double Q, double dt)
Integrate one step forward the cusp normal form (see Strogatz, 1994) with an additive Wiener process, with an Euler-Maruyama scheme.
Parameters
[in] state Present state.
[in] r Parameter r.
[in] h Parameter h.
[in] noiseSample GSL matrix of noise realizations for each time step.
[in] Q Noise intensity.
[in] dt Time step.
Returns
GSL vector of the future state.
Definition at line 200 of file SDESolvers.hpp.
References additiveWienerField(), and cuspField().
Referenced by generateCuspAdditiveWienerEM().
gsl_matrix * generateCuspAdditiveWienerEM (gsl_vector * state, double r, double h, gsl_matrix * noiseSamples, double Q, double length, double dt, int sampling, double spinup)
Integrate the cusp normal form (see Strogatz, 1994) with additive Wiener process, with an Euler-Maruyama scheme.
Parameters
[in] state Initial state.
[in] r Parameter .
[in] h Parameter .
[in] noiseSamples GSL matrix of noise realizations for each time step.
[in] Q Noise intensity.
[in] length Length of integration.
[in] dt Time step.
[in] sampling Step between each sampled state.
[in] spinup Lenght of initial spinup period to discard.
Returns
GSL matrix recording the integration.
Definition at line 53 of file SDESolvers.hpp.
References cuspAdditiveWienerEM().
gsl_matrix * generateCuspAdditiveWienerEM (gsl_vector * state, double r, gsl_vector * hTransient, gsl_matrix * noiseSamples, double Q, double length, double dt, int sampling, double spinup)
Transient integration of the cusp normal form (see Strogatz, 1994) with additive Wiener process, with an Euler-Maruyama scheme.
Parameters
[in] state Initial state.
[in] r Parameter .
[in] hTransient GSL vector of the variable parameter for each time step.
[in] noiseSamples GSL matrix of noise realizations for each time step.
[in] Q Noise intensity.
[in] length Length of integration.
[in] dt Time step.
[in] sampling Step between each sampled state.
[in] spinup Lenght of initial spinup period to discard.
Returns
GSL matrix recording the integration.
Definition at line 124 of file SDESolvers.hpp.
References cuspAdditiveWienerEM().
gsl_matrix * generateLorenzLinearWienerEM (gsl_vector * state, double rho, double sigma, double beta, gsl_matrix * noiseSamples, double Q, double length, double dt, int sampling, double spinup)
Integrate the Lorenz, 1963 with multiplicative linear Wiener process, with an Euler-Maruyama Scheme.
Parameters
[in] state Initial state.
[in] rho Parameter .
[in] sigma Parameter .
[in] beta Parameter .
[in] noiseSamples GSL matrix of noise realizations for each time step.
[in] Q Noise intensity.
[in] length Length of integration.
[in] dt Time step.
[in] sampling Step between each sampled state.
[in] spinup Lenght of initial spinup period to discard.
Returns
GSL matrix recording the integration.
Definition at line 242 of file SDESolvers.hpp.
References lorenzLinearWienerEM().
gsl_vector * linearWienerField (gsl_vector * state, double Q, gsl_vector * noiseSample)
Get the field of the multiplicative linear Wiener process.
Parameters
[in] state Present state.
[in] Q Noise intensity.
[in] noiseSample GSL vector of noise realization for this time step.
Returns
GSL vector of the field at the state.
Definition at line 363 of file SDESolvers.hpp.
Referenced by lorenzLinearWienerEM().
gsl_vector * lorenzLinearWienerEM (gsl_vector * state, double rho, double sigma, double beta, gsl_vector * noiseSample, double Q, double dt)
Integrate one step the Lorenz, 1963 with multiplicative linear Wiener process, with an Euler-Maruyama Scheme.
Parameters
[in] state Initial state.
[in] rho Parameter .
[in] sigma Parameter .
[in] beta Parameter .
[in] noiseSample GSL matrix of noise realizations for each time step.
[in] Q Noise intensity.
[in] dt Time step.
Returns
GSL matrix recording the integration.
Definition at line 311 of file SDESolvers.hpp.
References linearWienerField(), and lorenzField().
Referenced by generateLorenzLinearWienerEM().