ATSuite C++: transferOperator.hpp File Reference
transferOperator.hpp File Reference
Calculate discretized approximation of transfer operators from time series.
#include <iostream>
#include <vector>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_vector_uint.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_matrix_uint.h>
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <ATSuite/atmatrix.hpp>
#include <ATSuite/atmarkov.hpp>
Typedefs
typedef Eigen::Triplet< double > triplet
Eigen triplet of double.
typedef std::vector< triplet > tripletVector
STD vector of Eigen triplet of double.
typedef Eigen::Triplet< size_t > tripletUInt
Eigen triplet of integer.
typedef std::vector< tripletUInt > tripletUIntVector
STD vector of Eigen triplet of integer.
typedef Eigen::SparseMatrix< double, Eigen::ColMajor > SpMatCSC
Eigen CSC matrix of double type.
typedef Eigen::SparseMatrix< double, Eigen::RowMajor > SpMatCSR
Eigen CSR matrix of double type.
Functions
void getTransitionMatrix (const gsl_matrix_uint *gridMem, const size_t N, SpMatCSR *P, SpMatCSR *Q, gsl_vector *initDist, gsl_vector *finalDist)
Get the transition matrices from the membership matrix.
void getTransitionMatrix (const gsl_matrix *initStates, const gsl_matrix *finalStates, const std::vector< gsl_vector * > *gridBounds, SpMatCSR *P, SpMatCSR *Q, gsl_vector *initDist, gsl_vector *finalDist)
Get the transition matrices from the initial and final states of trajectories.
void getTransitionMatrix (const gsl_matrix *states, const std::vector< gsl_vector * > *gridBounds, const size_t tauStep, SpMatCSR *P, SpMatCSR *Q, gsl_vector *initDist, gsl_vector *finalDist)
Get the transition matrices from a single long trajectory.
gsl_matrix_uint * getGridMembership (const gsl_matrix *initStates, const gsl_matrix *finalStates, const std::vector< gsl_vector * > *gridBounds)
Get membership matrix from initial and final states for a grid.
gsl_matrix_uint * getGridMembership (const gsl_matrix *states, const std::vector< gsl_vector * > *gridBounds, const size_t tauStep)
Get the grid membership matrix from a single long trajectory.
gsl_vector_uint * getGridMembership (const gsl_matrix *states, const std::vector< gsl_vector * > *gridBounds)
Get the grid membership vector from a single long trajectory.
gsl_matrix_uint * getGridMembership (gsl_vector_uint *gridMemVect, const size_t tauStep)
Get the grid membership matrix from the membership vector for a given lag.
int getBoxMembership (gsl_vector *state, const std::vector< gsl_vector * > *gridBounds)
Get membership to a grid box of a single realization.
std::vector< gsl_vector * > * getGridRect (size_t dim, size_t nx, double xmin, double xmax)
Get a uniform rectangular grid.
std::vector< gsl_vector * > * getGridRect (gsl_vector_uint *nx, gsl_vector *xmin, gsl_vector *xmax)
Get a uniform rectangular grid.
void writeGridRect (FILE *fp, std::vector< gsl_vector * > *gridBounds, bool verbose=false)
Print a uniform rectangular grid to file.
Detailed Description
Calculate discretized approximation of transfer operators from time series. The result is given as forward and backward Markov transition matrices and their distributions.
Definition in file transferOperator.hpp.
Function Documentation
int getBoxMembership (gsl_vector * state, const std::vector< gsl_vector * > * gridBounds)
Get membership to a grid box of a single realization.
Parameters
[in] state GSL vector of a single state.
[in] gridBounds STD vector of gsl_vector of grid box bounds for each dimension.
Returns
Box index to which the state belongs.
Definition at line 409 of file transferOperator.hpp.
Referenced by getGridMembership().
gsl_matrix_uint * getGridMembership (const gsl_matrix * initStates, const gsl_matrix * finalStates, const std::vector< gsl_vector * > * gridBounds)
Get membership matrix from initial and final states for a grid.
Parameters
[in] initStates GSL matrix of initial states.
[in] finalStates GSL matrix of final states.
[in] gridBounds STD vector of gsl_vector of grid box bounds for each dimension.
Returns
GSL grid membership matrix.
Definition at line 194 of file transferOperator.hpp.
References getBoxMembership().
Referenced by getGridMembership(), and getTransitionMatrix().
gsl_matrix_uint * getGridMembership (const gsl_matrix * states, const std::vector< gsl_vector * > * gridBounds, const size_t tauStep)
Get the grid membership matrix from a single long trajectory.
Parameters
[in] states GSL matrix of states for each time step.
[in] gridBounds STD vector of gsl_vector of grid box bounds for each dimension.
[in] tauStep Lag used to calculate the transitions.
Returns
GSL grid membership matrix.
Definition at line 312 of file transferOperator.hpp.
References getGridMembership().
gsl_vector_uint * getGridMembership (const gsl_matrix * states, const std::vector< gsl_vector * > * gridBounds)
Get the grid membership vector from a single long trajectory.
Parameters
[in] states GSL matrix of states for each time step.
[in] gridBounds STD vector of gsl_vector of grid box bounds for each dimension.
Returns
GSL grid membership vector.
Definition at line 346 of file transferOperator.hpp.
References getBoxMembership().
gsl_matrix_uint * getGridMembership (gsl_vector_uint * gridMemVect, const size_t tauStep)
Get the grid membership matrix from the membership vector for a given lag.
Parameters
[in] gridMemVect Grid membership vector of a long trajectory for a grid.
[in] tauStep Lag used to calculate the transitions.
Returns
GSL grid membership matrix.
Definition at line 382 of file transferOperator.hpp.
std::vector< gsl_vector * > * getGridRect (size_t dim, size_t nx, double xmin, double xmax)
Get a uniform rectangular grid identically for each dimension.
Parameters
[in] dim Number of dimensions.
[in] nx Number of boxes, identically for each dimension.
[in] xmin Minimum box limit, identically for each dimension.
[in] xmax Maximum box limit, identically for each dimension.
Returns
STD vector of gsl_vectors of grid box bounds for each dimension.
Definition at line 459 of file transferOperator.hpp.
std::vector< gsl_vector * > * getGridRect (gsl_vector_uint * nx, gsl_vector * xmin, gsl_vector * xmax)
Get a uniform rectangular grid with specific bounds for each dimension.
Parameters
[in] nx GSL vector giving the number of boxes for each dimension.
[in] xmin GSL vector giving the minimum box limit for each dimension.
[in] xmax GSL vector giving the maximum box limit for each dimension.
Returns
STD vector of gsl_vectors of grid box bounds for each dimension.
Definition at line 490 of file transferOperator.hpp.
void getTransitionMatrix (const gsl_matrix_uint * gridMem, const size_t N, SpMatCSR * P, SpMatCSR * Q, gsl_vector * initDist, gsl_vector * finalDist)
Get the forward and backward transition matrices and distributions from the membership matrix.
Parameters
[in] gridMem GSL grid membership matrix.
[in] N Number of grid boxes.
[out] P Eigen CSR forward transition matrix.
[out] Q Eigen CSR backward transition matrix.
[out] initDist GSL vector of initial distribution.
[out] finalDist GSL vector of final distribution.
Definition at line 76 of file transferOperator.hpp.
References getColSum(), getRowSum(), normalizeVector(), and toLeftStochastic().
void getTransitionMatrix (const gsl_matrix * initStates, const gsl_matrix * finalStates, const std::vector< gsl_vector * > * gridBounds, SpMatCSR * P, SpMatCSR * Q, gsl_vector * initDist, gsl_vector * finalDist)
Get the forward and backward transition matrices and distributions from the initial and final states of trajectories.
Parameters
[in] initStates GSL matrix of initial states.
[in] finalStates GSL matrix of final states.
[in] gridBounds STD vector of gsl_vector of grid box bounds for each dimension.
[out] P Eigen CSR forward transition matrix.
[out] Q Eigen CSR backward transition matrix.
[out] initDist GSL vector of initial distribution.
[out] finalDist GSL vector of final distribution.
Definition at line 129 of file transferOperator.hpp.
References getColSum(), getGridMembership(), getRowSum(), normalizeVector(), and toLeftStochastic().
void getTransitionMatrix (const gsl_matrix * states, const std::vector< gsl_vector * > * gridBounds, const size_t tauStep, SpMatCSR * P, SpMatCSR * Q, gsl_vector * initDist, gsl_vector * finalDist)
Get the forward and backward transition matrices and distributions from a single long trajectory.
Parameters
[in] states GSL matrix of states for each time step.
[in] gridBounds STD vector of gsl_vector of grid box bounds for each dimension.
[in] tauStep Lag used to calculate the transitions.
[out] P Eigen CSR forward transition matrix.
[out] Q Eigen CSR backward transition matrix.
[out] initDist GSL vector of initial distribution.
[out] finalDist GSL vector of final distribution.
Definition at line 246 of file transferOperator.hpp.
References getColSum(), getGridMembership(), getRowSum(), normalizeVector(), and toLeftStochastic().
void writeGridRect (FILE * fp, std::vector< gsl_vector * > * gridBounds, bool verbose = false)
Print a uniform rectangular grid to file.
Parameters
[in] fp File descriptor of the file to which to print the grid.
[in] gridBounds STD vector of gsl_vector of grid box bounds for each dimension.
[in] verbose If true, also print to the standard output.
Definition at line 521 of file transferOperator.hpp.